version: "2"
services:
  discovery:
    environment:
      TAG: DISCOVERY
    build: ./discovery
    container_name: discovery
    restart: on-failure
    ports:
      - "8761:8761"
    env_file:
      - .env

  gateway:
    environment:
      TAG: gateway
    build: ./gateway
    container_name: gateway
    restart: on-failure
    ports:
      - "8079:8079"
    env_file:
      - .env
    depends_on:
      - discovery

  swagger:
    environment:
      TAG: swagger
    build: ./swagger
    container_name: swagger
    restart: on-failure
    network_mode: "host"
    env_file:
      - .env