spring:
  application:
    name: swagger

server:
  port: 8080

client:
  client-id: web-client

springdoc:
  swagger-ui:
    urls:
      - name: Location
        url: http://167.71.192.132:8082/v3/api-docs
      - name: Profile
        url: http://167.71.192.132:8083/v3/api-docs
      - name: Vehicle
        url: http://167.71.192.132:8084/v3/api-docs
    url: /v3/api-docs
    path: /
    oauth:
      client-id: ${client.client-id}
      use-pkce-with-authorization-code-grant: true
    oauth2-redirect-url: ${SWAGGER_DOMAIN}/swagger-ui/oauth2-redirect.html