spring:
  application:
    name: swagger

server:
  port: 8080

client:
  client-id: web-client

springdoc:
  swagger-ui:
    urls:
      - name: Location
        url: https://api.devsphere.id.vn/location/v3/api-docs
      - name: Profile
        url: https://api.devsphere.id.vn/profile/v3/api-docs
      - name: Vehicle
        url: https://api.devsphere.id.vn/vehicle/v3/api-docs
      - name: Trip
        url: https://api.devsphere.id.vn/trip/v3/api-docs
      - name: Booking
        url: https://api.devsphere.id.vn/booking/v3/api-docs
      - name: Statistic
        url: https://api.devsphere.id.vn/statistics/v3/api-docs
    url: /v3/api-docs
    path: /
    oauth:
      client-id: ${client.client-id}
      use-pkce-with-authorization-code-grant: true
    oauth2-redirect-url: ${SWAGGER_DOMAIN}/swagger-ui/oauth2-redirect.html